---
layout: post
title: ' 예외 처리 '
subtitle: ' 2024년 2월 5일 월요일 '
catalog: true
category: log
subcategory: weekly
tags:
  - log
  - february
  - 2024
  - python
  - fastapi

---

# Today I Learned

## 날짜

2024년 2월 5일 월요일

## 내용

 이전에 진행했던 Task들을 마무리했다. 로컬에서는 문제없이 작동한다는 것을 확인했기 떄문에, 테스트 서버에서 확인이 필요했다. logging문으로 구체적인 예외 메시지를 확인할 수 있었는데, 특정 데이터가 None일 때 오류가 발생했다. 오류가 난 필드는 shop이 꼭 가지고 있어야 하는 데이터였기 때문에 이상했다. 테스트 서버의 데이터베이스를 확인해보니 모든 필드의 값이 None으로 되어있는 뜬금없는 데이터가 들어있었다. 그 레코드 하나를 지우면 해결될 일이지만, 실제 서버에서 이런일이 발생했다면 저 뜬금없는 레코드 하나때문에 작동을 안하고, 찾을려고 이리저리 뒤져볼 모습을 생각하니 해프닝으로 넘어갈 일은 아니라고 생각했다.

 혹여나 있을 잘못된 데이터로 동작이 멈추지 않도록 구현하는 부분도 신경써야겠다. 개발하면서 NoneType 관련된 오류가 많이 나는 이유도 내가 이 부분이 부족해서가 아닐까.

## 회고

 내일 오전엔 제발 메일이 와있었으면 좋겠다.
